#!/usr/bin/env bash
#If 9, say Hi!

counter=1
while [ "$counter" -le 10 ]
do
	if [ "$counter" -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
counter=$((counter+1))
done
