#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

h=1
while [ "$h" -le 10 ]
do
if [ "$h" -eq 8 ]
then
echo "good luck"
elif [ "$h" -eq 4 ]
then
echo "bad luck"
else
echo "Best School"
fi
h=$((h+1))
done
