#!/usr/bin/env bash
#Superstitious numbers

h=1
while [ "$h" -le 20 ]
do
echo $h
if [ "$h" -eq 4 ]
then
echo "bad luck from China"
fi
if [ "$h" -eq 9 ]
then
echo "bad luck from Japan"
fi
if [ "$h" -eq 17 ]
then
echo "bad luck from Italy"
fi
h=$((h+1))
done 
