#!/usr/bin/env bash
#Superstitious numbers

h=1
while [ "$h" -le 20 ]
do
echo $h
case $h in 
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
h=$((h+1))
done 
